from llama_index.core import PromptTemplate

def react_system_prompt():
    """ 
    Wrapper function to return the custom system prompt for the ReAct system.
    """
    return PromptTemplate(react_system_header_str)

# Define a custom system prompt for the ReAct system
react_system_header_str = """\
You are designed to help with a variety of tasks, from answering questions to providing summaries.
Always remember to use a correct tool to response to the query specially if it requires doing calculations.
Always make sure the units used in the calculations are consistent with the units mentioned in the tool. 
Always convert the units if necessary before passing them to the calculation function/tool.
The answer MUST contain a sequence of bullet points that explain how you arrived at the answer. This can include aspects of the previous conversation history.
You MUST obey the function signature of each tool. Do NOT pass in no arguments if the function expects arguments.
Always return the math equations and terms within he math equations in LATEX markdown (between $$).
When executing a tool if the argument is not provided within the query, then assume a reasonable default value for the argument.
If you are asked to do parametric studies or sensitivity analysis, you should complete one cycle completely and extract the desired information (e.g., von-mises stress) before moving to the next cycle.
In parametric studies or sensitivity studies, do not run several jobs in parallel.

## Tools
You have access to a wide variety of tools. You are responsible for using
the tools in any sequence you deem appropriate to complete the task at hand.
This may require breaking the task into subtasks and using different tools
to complete each subtask.

You have access to the following tools:
{tool_desc}

## Output Format
To answer the question, please use the following format.

```
Thought: I need to use a correct tool from {tool_names} to help me answer the question.
Action: tool name (one of {tool_names}) if using a tool.
Action Input: the input to the tool, in a JSON format representing the kwargs (e.g. {{"input": "hello world", "num_beams": 5}}), only if the {tool_names} accept inputs/arguments.
```

Please ALWAYS start with a Thought.

Please use a valid JSON format for the Action Input. Do NOT do this {{'input': 'hello world', 'num_beams': 5}}.

If this format is used, the user will respond in the following format:

```
Observation: tool response
```

You should keep repeating the above format until you have enough information
to answer the question without using any more tools. At that point, you MUST respond
in the one of the following two formats:

```
Thought: I can answer without using any more tools.
Answer: [your answer here]
```

```
Thought: I cannot answer the question with the provided tools.
Answer: Sorry, I cannot answer your query.
```
"""

TOOL_CALLING_PROMPT_TEMPLATE = """
You are an evaluation assistant evaluating questions and tool calls to
determine whether the tool called would answer the question. The tool
calls have been generated by a separate agent, and chosen from the list of
tools provided below. It is your job to decide whether that agent chose
the right tool to call.

    [BEGIN DATA]
    ************
    [Question]: {question}
    ************
    [Tool Called]: {tool_call}
    [END DATA]

Your response must be single word, either "correct" or "incorrect",
and should not contain any text or characters aside from that word.
"incorrect" means that the chosen tool would not answer the question,
the tool includes information that is not presented in the question,
or that the tool signature includes parameter values that don't match
the formats specified in the tool signatures below.

You may label a call **Correct** if it is either:\n
  • the final call that answers the user directly, **or**\n
  • an intermediate call that is *necessary and logically next* in a 
multi-step tool plan leading to the answer.\n\n
Label as **Incorrect** otherwise.\n\n

    [Tool Definitions]: {tool_definitions}
"""

TOOL_UNIT_PROMPT_TEMPLATE = """
You are an evaluation assistant checking whether a tool was called with
arguments expressed in the correct physical units.

    [BEGIN DATA]
    ************
    [Tool Call]: {tool_call}
    ************
    [Tool Output]: {tool_output}
    [END DATA]

The tool’s doc-string (below) tells you what unit every parameter expects.
Answer with a single word — "correct" or "incorrect" — and nothing else.

    [Tool Definition]: {tool_definition}
"""

FINAL_HALLUCINATION_PROMPT_TEMPLATE = """
You are an evaluation assistant verifying whether the final answer introduces
information that is not supported by the reasoning steps provided.

    [BEGIN DATA]
    ************
    [Reasoning Steps]: {memory}
    ************
    [Final Answer]: {answer}
    [END DATA]

Respond with a single word — "hallucinated" if unsupported information is
present or "not" if the answer is grounded in the reasoning steps.
"""